"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
*
Copyright 2020 Alibaba Group Holding Limited.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import groot.sdk.model_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class CreateNewGraphBackupRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___CreateNewGraphBackupRequest = CreateNewGraphBackupRequest

@typing_extensions.final
class CreateNewGraphBackupResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BACKUPID_FIELD_NUMBER: builtins.int
    backupId: builtins.int
    def __init__(
        self,
        *,
        backupId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["backupId", b"backupId"]) -> None: ...

global___CreateNewGraphBackupResponse = CreateNewGraphBackupResponse

@typing_extensions.final
class DeleteGraphBackupRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BACKUPID_FIELD_NUMBER: builtins.int
    backupId: builtins.int
    def __init__(
        self,
        *,
        backupId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["backupId", b"backupId"]) -> None: ...

global___DeleteGraphBackupRequest = DeleteGraphBackupRequest

@typing_extensions.final
class DeleteGraphBackupResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___DeleteGraphBackupResponse = DeleteGraphBackupResponse

@typing_extensions.final
class PurgeOldGraphBackupsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEEPALIVENUMBER_FIELD_NUMBER: builtins.int
    keepAliveNumber: builtins.int
    def __init__(
        self,
        *,
        keepAliveNumber: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["keepAliveNumber", b"keepAliveNumber"]) -> None: ...

global___PurgeOldGraphBackupsRequest = PurgeOldGraphBackupsRequest

@typing_extensions.final
class PurgeOldGraphBackupsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___PurgeOldGraphBackupsResponse = PurgeOldGraphBackupsResponse

@typing_extensions.final
class RestoreFromGraphBackupRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BACKUPID_FIELD_NUMBER: builtins.int
    META_RESTORE_PATH_FIELD_NUMBER: builtins.int
    STORE_RESTORE_PATH_FIELD_NUMBER: builtins.int
    backupId: builtins.int
    meta_restore_path: builtins.str
    store_restore_path: builtins.str
    def __init__(
        self,
        *,
        backupId: builtins.int = ...,
        meta_restore_path: builtins.str = ...,
        store_restore_path: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["backupId", b"backupId", "meta_restore_path", b"meta_restore_path", "store_restore_path", b"store_restore_path"]) -> None: ...

global___RestoreFromGraphBackupRequest = RestoreFromGraphBackupRequest

@typing_extensions.final
class RestoreFromGraphBackupResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___RestoreFromGraphBackupResponse = RestoreFromGraphBackupResponse

@typing_extensions.final
class VerifyGraphBackupRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BACKUPID_FIELD_NUMBER: builtins.int
    backupId: builtins.int
    def __init__(
        self,
        *,
        backupId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["backupId", b"backupId"]) -> None: ...

global___VerifyGraphBackupRequest = VerifyGraphBackupRequest

@typing_extensions.final
class VerifyGraphBackupResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ISOK_FIELD_NUMBER: builtins.int
    ERRMSG_FIELD_NUMBER: builtins.int
    isOk: builtins.bool
    errMsg: builtins.str
    def __init__(
        self,
        *,
        isOk: builtins.bool = ...,
        errMsg: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["errMsg", b"errMsg", "isOk", b"isOk"]) -> None: ...

global___VerifyGraphBackupResponse = VerifyGraphBackupResponse

@typing_extensions.final
class GetGraphBackupInfoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GetGraphBackupInfoRequest = GetGraphBackupInfoRequest

@typing_extensions.final
class GetGraphBackupInfoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BACKUPINFOLIST_FIELD_NUMBER: builtins.int
    @property
    def backupInfoList(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[groot.sdk.model_pb2.BackupInfoPb]: ...
    def __init__(
        self,
        *,
        backupInfoList: collections.abc.Iterable[groot.sdk.model_pb2.BackupInfoPb] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["backupInfoList", b"backupInfoList"]) -> None: ...

global___GetGraphBackupInfoResponse = GetGraphBackupInfoResponse
