ICEBERG_ALIAS: str
SQLITE_ALIAS: str
SQLITE_STATE_ALIAS: str
POSTGRES_STATE_ALIAS: str
SQLITE_HISTORICAL_ALIAS: str
SQLITE_IMMUTABLE_ALIAS: str
POSTGRES_HISTORICAL_ALIAS: str
POSTGRES_IMMUTABLE_ALIAS: str
CONNECTION_BACKEND_ALIASES: dict[str, str]
