# Generated by Django 5.1.1 on 2024-09-12 14:26

import django.core.validators
import milea_base.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milea_demo', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultmodal',
            name='progress',
            field=milea_base.fields.ProgressBarField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
