# Generated by Django 5.0.9 on 2024-09-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_voice', '0011_alter_sitevoiceinfo_maintainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicedelivery',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='voicedelivery',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='voicedelivery',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='voicemaintainer',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
