# Generated by Django 5.0.9 on 2024-09-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0190_nested_modules'),
        ('extras', '0121_customfield_related_object_filter'),
        ('sop_voice', '0014_voicesda_check_start_end_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='voicesda',
            name='check_start_end_unique',
        ),
        migrations.AddConstraint(
            model_name='voicesda',
            constraint=models.UniqueConstraint(fields=('start',), name='sop_voice_voicesda_unique_start_number', violation_error_message='Start number must be unique.'),
        ),
        migrations.AddConstraint(
            model_name='voicesda',
            constraint=models.UniqueConstraint(fields=('end',), name='sop_voice_voicesda_unique_name', violation_error_message='End number must be unique.'),
        ),
    ]
