# Generated by Django 5.0.9 on 2024-09-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0044_circuit_groups'),
        ('dcim', '0190_nested_modules'),
        ('extras', '0121_customfield_related_object_filter'),
        ('sop_voice', '0015_remove_voicesda_check_start_end_unique_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='voicesda',
            name='sop_voice_voicesda_unique_name',
        ),
        migrations.AddConstraint(
            model_name='voicedelivery',
            constraint=models.UniqueConstraint(fields=('ndi',), name='sop_voice_voicedelivery_unique_ndi', violation_error_message='NDI must be unique.'),
        ),
        migrations.AddConstraint(
            model_name='voicedelivery',
            constraint=models.UniqueConstraint(fields=('dto',), name='sop_voice_voicedelivery_unique_dto', violation_error_message='DTO must be unique.'),
        ),
        migrations.AddConstraint(
            model_name='voicedelivery',
            constraint=models.UniqueConstraint(fields=('delivery', 'site'), name='sop_voice_voicedelivery_unique_delivery_method_site', violation_error_message='Delivery method must be unique in a site.'),
        ),
        migrations.AddConstraint(
            model_name='voicemaintainer',
            constraint=models.UniqueConstraint(fields=('name',), name='sop_voice_voicemaintainer_unique_name', violation_error_message='Maintainer name must be unique.'),
        ),
        migrations.AddConstraint(
            model_name='voicemaintainer',
            constraint=models.UniqueConstraint(fields=('slug',), name='sop_voice_voicemaintainer_unique_slug', violation_error_message='Maintainer slug must be unique.'),
        ),
        migrations.AddConstraint(
            model_name='voicesda',
            constraint=models.UniqueConstraint(fields=('end',), name='sop_voice_voicesda_unique_end_number', violation_error_message='End number must be unique.'),
        ),
        migrations.AddConstraint(
            model_name='voicesda',
            constraint=models.CheckConstraint(check=models.Q(('end__isnull', True), ('end__gt', models.F('start')), _connector='OR'), name='sop_voice_voicesda_check_end_number', violation_error_message='End number must be greater than start number.'),
        ),
    ]
