# Generated by Django 5.0.9 on 2024-10-01 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0190_nested_modules'),
        ('extras', '0121_customfield_related_object_filter'),
        ('sop_voice', '0017_remove_voicesda_sop_voice_voicesda_check_end_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='voicedelivery',
            name='sop_voice_voicedelivery_unique_dto',
        ),
        migrations.RemoveConstraint(
            model_name='voicesda',
            name='sop_voice_voicesda_end_greater_than_start',
        ),
        migrations.AlterField(
            model_name='voicesda',
            name='end',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='voicesda',
            name='site',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dcim.site'),
        ),
        migrations.AlterField(
            model_name='voicesda',
            name='start',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='voicesda',
            constraint=models.CheckConstraint(check=models.Q(('end__gte', models.F('start'))), name='sop_voice_voicesda_end_greater_than_start', violation_error_message='End number must be greater than or equal to start number.'),
        ),
    ]
