# Generated by Django 5.0.9 on 2024-10-01 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0044_circuit_groups'),
        ('dcim', '0190_nested_modules'),
        ('sop_voice', '0018_remove_voicedelivery_sop_voice_voicedelivery_unique_dto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevoiceinfo',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dcim.site'),
        ),
        migrations.AlterField(
            model_name='voicedelivery',
            name='channel_count',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voicedelivery',
            name='dto',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voicedelivery',
            name='ndi',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voicedelivery',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circuits.provider'),
        ),
        migrations.AlterField(
            model_name='voicedelivery',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcim.site'),
        ),
        migrations.AlterField(
            model_name='voicesda',
            name='end',
            field=models.PositiveBigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='voicesda',
            name='start',
            field=models.PositiveBigIntegerField(blank=True),
        ),
    ]
