# Generated by Django 5.0.9 on 2024-10-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0190_nested_modules'),
        ('extras', '0121_customfield_related_object_filter'),
        ('sop_voice', '0019_alter_sitevoiceinfo_site_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sitevoiceinfo',
            constraint=models.UniqueConstraint(fields=('site',), name='sop_voice_sitevoiceinfo_unique_site', violation_error_message='Site must be unique.'),
        ),
    ]
