'''
## This file is autogenerated from macrosynergy setup.py.

It contains version information for the macrosynergy package.

short_version: 0.1.33

version: 0.1.33

full_version: 0.1.33

git_revision: 05d0c1b5e12bad4efb77c7b6136a1b8aead3e4b8

release: True

'''
short_version: str = '0.1.33'
version: str = '0.1.33'
full_version: str = '0.1.33'
git_revision: str = '05d0c1b5e12bad4efb77c7b6136a1b8aead3e4b8'
release: bool = True
if not release:
    version = full_version
