from typing import Final

class Bars:
    @property
    def ha_bars(self): ...
    @property
    def ohlcvs(self): ...
    def write_ohlcv_to_parquet(self, file_path): ...
    def to_parquet(self): ...
    def add_ohlcv(self, ohlcv): ...
    @staticmethod
    def __new__(*args, **kwargs) -> Bars: ...
    def __lt__(self, value): ...
    def __init__(self, *args, **kwargs): ...
    def __hash__(self): ...
    def __eq__(self, value): ...

class OHLCV:
    @property
    def close(self): ...
    @property
    def high(self): ...
    @property
    def low(self): ...
    @property
    def open(self): ...
    @property
    def symbol(self): ...
    @property
    def time(self): ...
    @property
    def timestamp_ms(self): ...
    @property
    def volume(self): ...
    @staticmethod
    def __new__(*args, **kwargs) -> OHLCV: ...
    def __lt__(self, value): ...
    def __init__(self, *args, **kwargs): ...
    def __hash__(self): ...
    def __eq__(self, value): ...

