# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from com.terraquantum.role.v1.member import list_editable_members_pb2 as com_dot_terraquantum_dot_role_dot_v1_dot_member_dot_list__editable__members__pb2
from com.terraquantum.role.v1.member import list_project_groups_request_pb2 as com_dot_terraquantum_dot_role_dot_v1_dot_member_dot_list__project__groups__request__pb2
from com.terraquantum.role.v1.member import list_project_members_pb2 as com_dot_terraquantum_dot_role_dot_v1_dot_member_dot_list__project__members__pb2
from com.terraquantum.role.v1.member import list_user_groups_request_pb2 as com_dot_terraquantum_dot_role_dot_v1_dot_member_dot_list__user__groups__request__pb2
from com.terraquantum.role.v1.member import member_pb2 as com_dot_terraquantum_dot_role_dot_v1_dot_member_dot_member__pb2
from com.terraquantum.role.v1.member import object_ids_response_pb2 as com_dot_terraquantum_dot_role_dot_v1_dot_member_dot_object__ids__response__pb2


class MemberServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListProjectMembers = channel.unary_unary(
                '/com.terraquantum.role.v1.member.MemberService/ListProjectMembers',
                request_serializer=com_dot_terraquantum_dot_role_dot_v1_dot_member_dot_list__project__members__pb2.ListProjectMembersRequest.SerializeToString,
                response_deserializer=com_dot_terraquantum_dot_role_dot_v1_dot_member_dot_member__pb2.MemberListProto.FromString,
                )
        self.ListProjectGroups = channel.unary_unary(
                '/com.terraquantum.role.v1.member.MemberService/ListProjectGroups',
                request_serializer=com_dot_terraquantum_dot_role_dot_v1_dot_member_dot_list__project__groups__request__pb2.ListProjectGroupsRequest.SerializeToString,
                response_deserializer=com_dot_terraquantum_dot_role_dot_v1_dot_member_dot_member__pb2.MemberListProto.FromString,
                )
        self.ListEditableMembers = channel.unary_unary(
                '/com.terraquantum.role.v1.member.MemberService/ListEditableMembers',
                request_serializer=com_dot_terraquantum_dot_role_dot_v1_dot_member_dot_list__editable__members__pb2.ListEditableMembersRequest.SerializeToString,
                response_deserializer=com_dot_terraquantum_dot_role_dot_v1_dot_member_dot_member__pb2.MemberListProto.FromString,
                )
        self.ListUserGroups = channel.unary_unary(
                '/com.terraquantum.role.v1.member.MemberService/ListUserGroups',
                request_serializer=com_dot_terraquantum_dot_role_dot_v1_dot_member_dot_list__user__groups__request__pb2.ListUserGroupsRequest.SerializeToString,
                response_deserializer=com_dot_terraquantum_dot_role_dot_v1_dot_member_dot_object__ids__response__pb2.ObjectIdsListProto.FromString,
                )


class MemberServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListProjectMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProjectGroups(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEditableMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUserGroups(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemberServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListProjectMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProjectMembers,
                    request_deserializer=com_dot_terraquantum_dot_role_dot_v1_dot_member_dot_list__project__members__pb2.ListProjectMembersRequest.FromString,
                    response_serializer=com_dot_terraquantum_dot_role_dot_v1_dot_member_dot_member__pb2.MemberListProto.SerializeToString,
            ),
            'ListProjectGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProjectGroups,
                    request_deserializer=com_dot_terraquantum_dot_role_dot_v1_dot_member_dot_list__project__groups__request__pb2.ListProjectGroupsRequest.FromString,
                    response_serializer=com_dot_terraquantum_dot_role_dot_v1_dot_member_dot_member__pb2.MemberListProto.SerializeToString,
            ),
            'ListEditableMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEditableMembers,
                    request_deserializer=com_dot_terraquantum_dot_role_dot_v1_dot_member_dot_list__editable__members__pb2.ListEditableMembersRequest.FromString,
                    response_serializer=com_dot_terraquantum_dot_role_dot_v1_dot_member_dot_member__pb2.MemberListProto.SerializeToString,
            ),
            'ListUserGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUserGroups,
                    request_deserializer=com_dot_terraquantum_dot_role_dot_v1_dot_member_dot_list__user__groups__request__pb2.ListUserGroupsRequest.FromString,
                    response_serializer=com_dot_terraquantum_dot_role_dot_v1_dot_member_dot_object__ids__response__pb2.ObjectIdsListProto.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.terraquantum.role.v1.member.MemberService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MemberService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListProjectMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.terraquantum.role.v1.member.MemberService/ListProjectMembers',
            com_dot_terraquantum_dot_role_dot_v1_dot_member_dot_list__project__members__pb2.ListProjectMembersRequest.SerializeToString,
            com_dot_terraquantum_dot_role_dot_v1_dot_member_dot_member__pb2.MemberListProto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListProjectGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.terraquantum.role.v1.member.MemberService/ListProjectGroups',
            com_dot_terraquantum_dot_role_dot_v1_dot_member_dot_list__project__groups__request__pb2.ListProjectGroupsRequest.SerializeToString,
            com_dot_terraquantum_dot_role_dot_v1_dot_member_dot_member__pb2.MemberListProto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListEditableMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.terraquantum.role.v1.member.MemberService/ListEditableMembers',
            com_dot_terraquantum_dot_role_dot_v1_dot_member_dot_list__editable__members__pb2.ListEditableMembersRequest.SerializeToString,
            com_dot_terraquantum_dot_role_dot_v1_dot_member_dot_member__pb2.MemberListProto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListUserGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.terraquantum.role.v1.member.MemberService/ListUserGroups',
            com_dot_terraquantum_dot_role_dot_v1_dot_member_dot_list__user__groups__request__pb2.ListUserGroupsRequest.SerializeToString,
            com_dot_terraquantum_dot_role_dot_v1_dot_member_dot_object__ids__response__pb2.ObjectIdsListProto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
