TEST_IP = "192.168.88.45"

MOCK_RESPONSE = {
    "master": {
        "type": "minidsp",
        "name": "master",
        "masterVolume": -1.5,
        "mute": False,
        "slots": [
            {
                "id": "1",
                "last": "Fast Five",
                "active": True,
                "gains": [{"id": "1", "value": 0.0}, {"id": "2", "value": 0.0}],
                "mutes": [{"id": "1", "value": False}, {"id": "2", "value": False}],
                "canActivate": True,
                "inputs": 2,
                "outputs": 4,
            },
            {
                "id": "2",
                "last": "Empty",
                "active": False,
                "gains": [{"id": "1", "value": 0.0}, {"id": "2", "value": 0.0}],
                "mutes": [{"id": "1", "value": False}, {"id": "2", "value": False}],
                "canActivate": True,
                "inputs": 2,
                "outputs": 4,
            },
            {
                "id": "3",
                "last": "Empty",
                "active": False,
                "gains": [{"id": "1", "value": 0.0}, {"id": "2", "value": 0.0}],
                "mutes": [{"id": "1", "value": False}, {"id": "2", "value": False}],
                "canActivate": True,
                "inputs": 2,
                "outputs": 4,
            },
            {
                "id": "4",
                "last": "Empty",
                "active": False,
                "gains": [{"id": "1", "value": 0.0}, {"id": "2", "value": 0.0}],
                "mutes": [{"id": "1", "value": False}, {"id": "2", "value": False}],
                "canActivate": True,
                "inputs": 2,
                "outputs": 4,
            },
        ],
    },
    "master2": {
        "type": "minidsp",
        "name": "master2",
        "masterVolume": -1.5,
        "mute": False,
        "slots": [
            {
                "id": "1",
                "last": "Fast Five",
                "active": True,
                "gains": [{"id": "1", "value": 0}, {"id": "2", "value": 0}],
                "mutes": [{"id": "1", "value": False}, {"id": "2", "value": False}],
                "canActivate": True,
                "inputs": 2,
                "outputs": 4,
            },
            {
                "id": "2",
                "last": "Empty",
                "active": False,
                "gains": [{"id": "1", "value": 0.0}, {"id": "2", "value": 0.0}],
                "mutes": [{"id": "1", "value": False}, {"id": "2", "value": False}],
                "canActivate": True,
                "inputs": 2,
                "outputs": 4,
            },
            {
                "id": "3",
                "last": "Empty",
                "active": False,
                "gains": [{"id": "1", "value": 0.0}, {"id": "2", "value": 0.0}],
                "mutes": [{"id": "1", "value": False}, {"id": "2", "value": False}],
                "canActivate": True,
                "inputs": 2,
                "outputs": 4,
            },
            {
                "id": "4",
                "last": "Empty",
                "active": False,
                "gains": [{"id": "1", "value": 0.0}, {"id": "2", "value": 0.0}],
                "mutes": [{"id": "1", "value": False}, {"id": "2", "value": False}],
                "canActivate": True,
                "inputs": 2,
                "outputs": 4,
            },
        ],
    },
}
