from .horner import Horner
from .horner import HornerChiaDaThuc
from .horner import HornerTinhDaoHam
from .horner import HornerNhanDaThuc
from .noiSuyLagrange import LapBangTichLagrange
from .noiSuyLagrange import LapBangThuongLagrange
from .noiSuyLagrange import CalculateCy
from .noiSuyLagrange import DaThucLagrange
from .noiSuyNewton import TinhTySaiPhan
from .noiSuyNewton import DaThucNoiSuyNewton