# coding: utf-8

"""
    scibec

    scibec

    The version of the OpenAPI document: 1.14.2
    Contact: klaus.wakonig@psi.ch
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_scibec_openapi_client.models.device_filter import DeviceFilter

class TestDeviceFilter(unittest.TestCase):
    """DeviceFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceFilter:
        """Test DeviceFilter
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeviceFilter`
        """
        model = DeviceFilter()
        if include_optional:
            return DeviceFilter(
                offset = 0,
                limit = 100,
                skip = 0,
                order = None,
                fields = None,
                include = [
                    null
                    ]
            )
        else:
            return DeviceFilter(
        )
        """

    def testDeviceFilter(self):
        """Test DeviceFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
