# coding: utf-8

"""
    scibec

    scibec

    The version of the OpenAPI document: 1.14.2
    Contact: klaus.wakonig@psi.ch
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_scibec_openapi_client.api.device_controller_api import DeviceControllerApi


class TestDeviceControllerApi(unittest.TestCase):
    """DeviceControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DeviceControllerApi()

    def tearDown(self) -> None:
        pass

    def test_device_controller_count(self) -> None:
        """Test case for device_controller_count

        """
        pass

    def test_device_controller_create(self) -> None:
        """Test case for device_controller_create

        """
        pass

    def test_device_controller_delete_by_id(self) -> None:
        """Test case for device_controller_delete_by_id

        """
        pass

    def test_device_controller_find(self) -> None:
        """Test case for device_controller_find

        """
        pass

    def test_device_controller_find_by_id(self) -> None:
        """Test case for device_controller_find_by_id

        """
        pass

    def test_device_controller_update_all(self) -> None:
        """Test case for device_controller_update_all

        """
        pass

    def test_device_controller_update_by_id(self) -> None:
        """Test case for device_controller_update_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
