
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-02T13:07:40-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b2b64db574d87e7a8f11d97695e96485eb7e1b99",
 "version": "0.10.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
