# Generated by Django 5.0.8 on 2024-09-05 12:18

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0187_alter_device_vc_position'),
        ('extras', '0116_custom_link_button_color'),
        ('sop_infra', '0002_infraclassification_industrial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfraSizing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('ad_cumul_user', models.IntegerField()),
                ('est_cumul_user', models.IntegerField()),
                ('reco_bw', models.IntegerField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Sizing',
                'verbose_name_plural': 'Sizings',
            },
        ),
    ]
