# Generated by Django 5.0.8 on 2024-09-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0004_alter_infrasizing_ad_cumul_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrasizing',
            name='ad_cumul_user',
            field=models.CharField(default=None),
        ),
        migrations.AlterField(
            model_name='infrasizing',
            name='est_cumul_user',
            field=models.CharField(default=None),
        ),
        migrations.AlterField(
            model_name='infrasizing',
            name='reco_bw',
            field=models.CharField(default=None),
        ),
    ]
