# Generated by Django 5.0.8 on 2024-09-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0008_inframerakisdwan'),
    ]

    operations = [
        migrations.AddField(
            model_name='inframerakisdwan',
            name='master_location',
            field=models.CharField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inframerakisdwan',
            name='master_site',
            field=models.CharField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inframerakisdwan',
            name='migration_date',
            field=models.CharField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inframerakisdwan',
            name='monitor_in_starting',
            field=models.CharField(default='none'),
            preserve_default=False,
        ),
    ]
