# Generated by Django 5.0.9 on 2024-09-30 08:48

from django.db import migrations, models


def transfer_data(apps, schema_editor):
    InfraSizing = apps.get_model('sop_infra', 'InfraSizing')
    for instance in InfraSizing.objects.all():
        if instance.ad_cumul_user:
            try:
                instance.ad_cumul_user = int(instance.ad_cumul_user)
            except:
                instance.ad_cumul_user = None
        if instance.est_cumul_user:
            try:
                instance.est_cumul_user = int(instance.est_cumul_user)
            except:
                instance.est_cumul_user = None
        if instance.reco_bw:
            try:
                instance.reco_bw = int(instance.reco_bw)
            except:
                instance.reco_bw = None
        
        instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0013_alter_infraclassification_industrial_and_more'),
    ]

    operations = [
        migrations.RunPython(transfer_data),
        migrations.AlterField(
            model_name='infrasizing',
            name='ad_cumul_user',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infrasizing',
            name='est_cumul_user',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infrasizing',
            name='reco_bw',
            field=models.CharField(blank=True, null=True),
        ),
    ]

