# Copyright 2022 OpenSynergy Indonesia
# Copyright 2022 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl-3.0-standalone.html).
# pylint: disable=locally-disabled, manifest-required-author
{
    "name": "General Audit Worksheet - Understanding Entity and It's Environment",
    "version": "14.0.1.10.0",
    "website": "https://simetri-sinergi.id",
    "author": "OpenSynergy Indonesia, PT. Simetri Sinergi Indonesia",
    "license": "AGPL-3",
    "installable": True,
    "depends": [
        "ssi_general_audit",
    ],
    "data": [
        "security/ir_module_category_data.xml",
        "security/res_group_data.xml",
        "security/res_group/general_audit_ws_e78a3c6.xml",
        "security/res_group/general_audit_ws_a13a30e.xml",
        "security/res_group/general_audit_ws_bdcdfc5.xml",
        "security/res_group/general_audit_ws_c0d0898.xml",
        "security/res_group/general_audit_ws_f6a227.xml",
        "security/res_group/general_audit_ws_c0e0eec.xml",
        "security/res_group/general_audit_ws_a604795.xml",
        "security/res_group/general_audit_ws_ae11f7e.xml",
        "security/ir.model.access.csv",
        "security/ir_model_access/general_audit_ws_e78a3c6.xml",
        "security/ir_model_access/general_audit_ws_a13a30e.xml",
        "security/ir_model_access/general_audit_ws_bdcdfc5.xml",
        "security/ir_model_access/general_audit_ws_c0d0898.xml",
        "security/ir_model_access/general_audit_ws_f6a227.xml",
        "security/ir_model_access/general_audit_ws_c0e0eec.xml",
        "security/ir_model_access/general_audit_ws_a604795.xml",
        "security/ir_model_access/general_audit_ws_ae11f7e.xml",
        "security/ir_rule/general_audit_ws_e78a3c6.xml",
        "security/ir_rule/general_audit_ws_a13a30e.xml",
        "security/ir_rule/general_audit_ws_bdcdfc5.xml",
        "security/ir_rule/general_audit_ws_c0d0898.xml",
        "security/ir_rule/general_audit_ws_f6a227.xml",
        "security/ir_rule/general_audit_ws_c0e0eec.xml",
        "security/ir_rule/general_audit_ws_a604795.xml",
        "security/ir_rule/general_audit_ws_ae11f7e.xml",
        "data/ir_sequence/general_audit_ws_e78a3c6.xml",
        "data/ir_sequence/general_audit_ws_a13a30e.xml",
        "data/ir_sequence/general_audit_ws_bdcdfc5.xml",
        "data/ir_sequence/general_audit_ws_c0d0898.xml",
        "data/ir_sequence/general_audit_ws_f6a227.xml",
        "data/ir_sequence/general_audit_ws_c0e0eec.xml",
        "data/ir_sequence/general_audit_ws_a604795.xml",
        "data/ir_sequence/general_audit_ws_ae11f7e.xml",
        "data/sequence_template/general_audit_ws_e78a3c6.xml",
        "data/sequence_template/general_audit_ws_a13a30e.xml",
        "data/sequence_template/general_audit_ws_bdcdfc5.xml",
        "data/sequence_template/general_audit_ws_c0d0898.xml",
        "data/sequence_template/general_audit_ws_f6a227.xml",
        "data/sequence_template/general_audit_ws_c0e0eec.xml",
        "data/sequence_template/general_audit_ws_a604795.xml",
        "data/sequence_template/general_audit_ws_ae11f7e.xml",
        "data/policy_template/general_audit_ws_e78a3c6.xml",
        "data/policy_template/general_audit_ws_a13a30e.xml",
        "data/policy_template/general_audit_ws_bdcdfc5.xml",
        "data/policy_template/general_audit_ws_c0d0898.xml",
        "data/policy_template/general_audit_ws_f6a227.xml",
        "data/policy_template/general_audit_ws_c0e0eec.xml",
        "data/policy_template/general_audit_ws_a604795.xml",
        "data/policy_template/general_audit_ws_ae11f7e.xml",
        "data/approval_template/general_audit_ws_e78a3c6.xml",
        "data/approval_template/general_audit_ws_a13a30e.xml",
        "data/approval_template/general_audit_ws_bdcdfc5.xml",
        "data/approval_template/general_audit_ws_c0d0898.xml",
        "data/approval_template/general_audit_ws_f6a227.xml",
        "data/approval_template/general_audit_ws_c0e0eec.xml",
        "data/approval_template/general_audit_ws_a604795.xml",
        "data/approval_template/general_audit_ws_ae11f7e.xml",
        "data/general_audit_worksheet_type_data.xml",
        "menu.xml",
        "views/general_audit_class_transaction_views.xml",
        "views/general_audit_business_function_views.xml",
        "views/general_audit_business_document_views.xml",
        "views/general_audit_going_concern_category_views.xml",
        "views/general_audit_going_concern_views.xml",
        "views/general_audit_fs_preparation_step_views.xml",
        "views/general_audit_fraud_factor_category_views.xml",
        "views/general_audit_fraud_factor_views.xml",
        "views/general_audit_fraud_factor_indicator_views.xml",
        "views/general_audit_expert_type_views.xml",
        "views/general_audit_fraud_other_report_views.xml",
        "views/general_audit_ws_e78a3c6_views.xml",
        "views/general_audit_ws_a13a30e_views.xml",
        "views/general_audit_ws_bdcdfc5_views.xml",
        "views/general_audit_ws_c0d0898_views.xml",
        "views/general_audit_ws_f6a227_views.xml",
        "views/general_audit_ws_c0e0eec_views.xml",
        "views/general_audit_ws_a604795_views.xml",
        "views/general_audit_ws_ae11f7e_views.xml",
        "views/general_audit_standard_detail_views.xml",
        "views/general_audit_views.xml",
    ],
    "demo": [],
}
