from distutils.core import setup

setup(
    name='streamlit-core',
    packages=['streamlit-core'],
    version='0.1.0',
    license='MIT',
    description='Core functionality for various streamlit apps.',
    author='Value Engineering',
    author_email='software@valueengineering.dk',
    url='https://valueengineering.dk/',
    download_url='https://github.com/Value-Engineering-ApS/streamlit-core/archive/refs/tags/v0.1.0.tar.gz',
    #   keywords = ['SOME', 'MEANINGFULL', 'KEYWORDS'],
    install_requires=[
        'python-docx',
        'docxtpl',
        'docx2pdf',
        'jinja2',
        'numpy',
        'pandas',
        'shapely',
        'scipy',
        'streamlit',
    ],
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'Topic :: Software Development :: Build Tools',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
    ],
)
