
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-26T11:26:25-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "0ce8566641a5afe7040b57e791717415aa757cee",
 "version": "2.46.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
