# Generated by Django 5.0.8 on 2024-09-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0010_inframerakisdwan_nha_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraclassification',
            name='industrial',
            field=models.CharField(default='none'),
        ),
        migrations.AlterField(
            model_name='infraclassification',
            name='infrastructure',
            field=models.CharField(default='none'),
        ),
    ]
