# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: engine_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'engine_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import message_pb2 as message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x65ngine_service.proto\x12\x06gs.rpc\x1a\rmessage.proto2\x91\x01\n\rEngineService\x12>\n\x07RunStep\x12\x16.gs.rpc.RunStepRequest\x1a\x17.gs.rpc.RunStepResponse(\x01\x30\x01\x12@\n\tHeartBeat\x12\x18.gs.rpc.HeartBeatRequest\x1a\x19.gs.rpc.HeartBeatResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'engine_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENGINESERVICE']._serialized_start=48
  _globals['_ENGINESERVICE']._serialized_end=193
# @@protoc_insertion_point(module_scope)
