# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, and installs.

    The version of the OpenAPI document: 0.19.76
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nuon.models.service_app_config_template_type import ServiceAppConfigTemplateType

class TestServiceAppConfigTemplateType(unittest.TestCase):
    """ServiceAppConfigTemplateType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceAppConfigTemplateType(self):
        """Test ServiceAppConfigTemplateType"""
        # inst = ServiceAppConfigTemplateType()

if __name__ == '__main__':
    unittest.main()
