# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, and installs.

    The version of the OpenAPI document: 0.19.216
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nuon.models.app_runner_job_status import AppRunnerJobStatus

class TestAppRunnerJobStatus(unittest.TestCase):
    """AppRunnerJobStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppRunnerJobStatus(self):
        """Test AppRunnerJobStatus"""
        # inst = AppRunnerJobStatus()

if __name__ == '__main__':
    unittest.main()
