# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, and installs.

    The version of the OpenAPI document: 0.19.216
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nuon.models.app_runner_group_settings import AppRunnerGroupSettings

class TestAppRunnerGroupSettings(unittest.TestCase):
    """AppRunnerGroupSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppRunnerGroupSettings:
        """Test AppRunnerGroupSettings
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppRunnerGroupSettings`
        """
        model = AppRunnerGroupSettings()
        if include_optional:
            return AppRunnerGroupSettings(
                container_image_tag = '',
                container_image_url = '',
                created_at = '',
                created_by = nuon.models.app/account.app.Account(
                    account_type = 'auth0', 
                    created_at = '', 
                    email = '', 
                    id = '', 
                    org_ids = [
                        ''
                        ], 
                    permissions = {
                        'key' : 'unknown'
                        }, 
                    roles = [
                        nuon.models.app/role.app.Role(
                            created_by = nuon.models.app/account.app.Account(
                                created_at = '', 
                                email = '', 
                                id = '', 
                                permissions = {
                                    'key' : 'unknown'
                                    }, 
                                subject = '', 
                                updated_at = '', ), 
                            created_at = '', 
                            created_by_id = '', 
                            id = '', 
                            policies = [
                                nuon.models.app/policy.app.Policy(
                                    created_at = '', 
                                    created_by_id = '', 
                                    id = '', 
                                    name = 'org_admin', 
                                    permissions = {
                                        'key' : ''
                                        }, 
                                    role_id = '', 
                                    updated_at = '', )
                                ], 
                            role_type = 'org_admin', 
                            updated_at = '', )
                        ], 
                    subject = '', 
                    updated_at = '', ),
                created_by_id = '',
                env = '',
                heart_beat_timeout = 56,
                id = '',
                org_id = '',
                otel_collector_config = '',
                runner_api_url = '',
                runner_group_id = '',
                settings_refresh_timeout = 56,
                updated_at = ''
            )
        else:
            return AppRunnerGroupSettings(
        )
        """

    def testAppRunnerGroupSettings(self):
        """Test AppRunnerGroupSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
