# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, and installs.

    The version of the OpenAPI document: 0.19.87
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nuon.models.app_operation_status import AppOperationStatus

class TestAppOperationStatus(unittest.TestCase):
    """AppOperationStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppOperationStatus(self):
        """Test AppOperationStatus"""
        # inst = AppOperationStatus()

if __name__ == '__main__':
    unittest.main()
