# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, and installs.

    The version of the OpenAPI document: 0.19.76
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nuon.models.app_app_config_fmt import AppAppConfigFmt

class TestAppAppConfigFmt(unittest.TestCase):
    """AppAppConfigFmt unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppAppConfigFmt(self):
        """Test AppAppConfigFmt"""
        # inst = AppAppConfigFmt()

if __name__ == '__main__':
    unittest.main()
