# coding: utf-8

"""
    Nuon

    API for managing nuon apps, components, and installs.

    The version of the OpenAPI document: 0.19.162
    Contact: support@nuon.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nuon.models.app_account_type import AppAccountType

class TestAppAccountType(unittest.TestCase):
    """AppAccountType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppAccountType(self):
        """Test AppAccountType"""
        # inst = AppAccountType()

if __name__ == '__main__':
    unittest.main()
