
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-30T17:08:45+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d90cdd0a2520e36c552217a1c3ec4e4f856c0128",
 "version": "v0.5.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
