# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.22.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gitea
from gitea.models.license_template_info import LicenseTemplateInfo  # noqa: E501
from gitea.rest import ApiException


class TestLicenseTemplateInfo(unittest.TestCase):
    """LicenseTemplateInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLicenseTemplateInfo(self):
        """Test LicenseTemplateInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gitea.models.license_template_info.LicenseTemplateInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
