# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.22.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gitea
from gitea.models.id_assets_body1 import IdAssetsBody1  # noqa: E501
from gitea.rest import ApiException


class TestIdAssetsBody1(unittest.TestCase):
    """IdAssetsBody1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdAssetsBody1(self):
        """Test IdAssetsBody1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gitea.models.id_assets_body1.IdAssetsBody1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
