# Generated by Django 5.0.9 on 2024-09-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_voice', '0007_alter_voicedelivery_dto_alter_voicedelivery_ndi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicedelivery',
            name='channel_count',
            field=models.IntegerField(),
        ),
    ]
