# Generated by Django 5.0.9 on 2024-09-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0190_nested_modules'),
        ('extras', '0121_customfield_related_object_filter'),
        ('sop_voice', '0013_remove_voicedelivery_slug'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='voicesda',
            constraint=models.UniqueConstraint(fields=('start', 'end'), name='check_start_end_unique'),
        ),
    ]
