# Autogenerated by devscripts/update-version.py

__version__ = '2024.09.30.232929'

RELEASE_GIT_HEAD = 'f91645aceaf13926cf35be2c1dfef61b3aab97fb'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2024.09.30.232929dev'
