# Generated by Django 5.0.9 on 2024-09-23 12:20

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circuits', '0044_circuit_groups'),
        ('dcim', '0190_nested_modules'),
        ('extras', '0121_customfield_related_object_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('delivery', models.CharField()),
                ('channel_count', models.CharField()),
                ('status', models.CharField(max_length=30)),
                ('ndi', models.CharField(max_length=100)),
                ('dto', models.CharField(max_length=100)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_delivery_provider', to='circuits.provider')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_delivery_site', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Voice Delivery',
                'verbose_name_plural': 'Voice Deliveries',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoiceMaintainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField()),
                ('status', models.CharField(default='Unknown', max_length=30)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Voice Maintainer',
                'verbose_name_plural': 'Voice Maintainers',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteVoiceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('maintainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sop_voice.voicemaintainer')),
            ],
            options={
                'verbose_name': 'Information',
                'verbose_name_plural': 'Informations',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoiceSda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('start', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sda_list_delivery', to='sop_voice.voicedelivery')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'DID Range',
                'verbose_name_plural': 'DIDs',
                'ordering': ('start',),
                'abstract': False,
            },
        ),
    ]
