# Generated by Django 5.0.9 on 2024-09-25 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_voice', '0002_voicesda_site_alter_voicesda_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicesda',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sda_list_delivery', to='sop_voice.voicedelivery'),
        ),
    ]
