# Generated by Django 5.0.9 on 2024-09-26 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_voice', '0010_alter_voicedelivery_channel_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevoiceinfo',
            name='maintainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sop_voice.voicemaintainer'),
        ),
    ]
