# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: error/coordinator.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'error/coordinator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x65rror/coordinator.proto\x12\x06gs.rpc*\xf4\x04\n\x04\x43ode\x12\x06\n\x02OK\x10\x00\x12\r\n\tCANCELLED\x10\x01\x12\x14\n\x10INVALID_ARGUMENT\x10\x02\x12\x0b\n\x07TIMEOUT\x10\x03\x12\r\n\tNOT_FOUND\x10\x04\x12\x12\n\x0e\x41LREADY_EXISTS\x10\x05\x12\x16\n\x12RESOURCE_EXHAUSTED\x10\x06\x12\x11\n\rUNIMPLEMENTED\x10\x07\x12\x15\n\x11PERMISSION_DENIED\x10\x08\x12\x17\n\x13\x43OMPILATION_FAILURE\x10\t\x12\x0f\n\x0bPORT_IN_USE\x10\n\x12\x19\n\x15UNSUPPORTED_OPERATION\x10\x0b\x12\x11\n\rILLEGAL_STATE\x10\x0c\x12\x13\n\x0fNETWORK_FAILURE\x10\r\x12\x14\n\x10\x43ONNECTION_ERROR\x10\x64\x12\x12\n\x0eVINEYARD_ERROR\x10\x65\x12\x16\n\x12UDF_INTERNAL_ERROR\x10\x66\x12\r\n\tK8S_ERROR\x10g\x12\x17\n\x13GREMLIN_QUERY_ERROR\x10h\x12\x1a\n\x16RETRIES_EXCEEDED_ERROR\x10i\x12$\n ANALYTICAL_ENGINE_INTERNAL_ERROR\x10j\x12%\n!INTERACTIVE_ENGINE_INTERNAL_ERROR\x10k\x12\"\n\x1eLEARNING_ENGINE_INTERNAL_ERROR\x10l\x12\x1e\n\x1a\x43OORDINATOR_INTERNAL_ERROR\x10m\x12%\n!WORKER_RESULTS_INCONSISTENT_ERROR\x10n\x12\x11\n\rUNKNOWN_ERROR\x10o\x12\x0f\n\x0b\x46\x41TAL_ERROR\x10pb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'error.coordinator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CODE']._serialized_start=36
  _globals['_CODE']._serialized_end=664
# @@protoc_insertion_point(module_scope)
