# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .update_req_common_metric_period import UpdateReqCommonMetricPeriod
from .update_req_common_value_type import UpdateReqCommonValueType
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class UpdateReqCommon(UniversalBaseModel):
    metric_period: typing.Optional[UpdateReqCommonMetricPeriod] = None
    value_bool: typing.Optional[bool] = None
    value_numeric: typing.Optional[int] = None
    value_trait_id: typing.Optional[str] = None
    value_type: UpdateReqCommonValueType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
