import numpy as np

from typing import List

def mean_axis1_f32(a: np.ndarray, num_threads: int = 8) -> np.ndarray: ...
def mean_axis1_f64(a: np.ndarray, num_threads: int = 8) -> np.ndarray: ...
def corr_axis1_f32(
    a: np.ndarray,
    b: np.ndarray,
    num_threads: int = 8,
) -> np.ndarray: ...
def corr_axis1_f64(
    a: np.ndarray,
    b: np.ndarray,
    num_threads: int = 8,
) -> np.ndarray: ...
def fast_concat_2d_axis0_f32(arrays: List[np.ndarray]) -> np.ndarray: ...
def fast_concat_2d_axis0_f64(arrays: List[np.ndarray]) -> np.ndarray: ...
