# Generated by Django 5.0.9 on 2024-09-25 10:08

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('edu_async_tasks_core', '0002_task_type_and_status_data'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='runningtask',
            new_name='edu_async_t_profile_70c100_idx',
            old_name='async_task__profile_c97023_idx',
        ),
        migrations.AlterField(
            model_name='runningtask',
            name='options',
            field=models.JSONField(blank=True, null=True, verbose_name='Дополнительные опции задачи'),
        ),
    ]
